#O application.properties o application.yml pero no los 2
---
spring:
  cloud:
    config:
      server:
        git:
          #Testing lab 10 (you must commnet URI local git repository line below)
          uri: https://github.com/Yorso/microspring-config-data.git #Remote GitHub repository where microspring11-cloud-client-lab10.yml file exists
          
          #Testing "BONUS - More Encryption" section (you must commnet URI remote GitHub repository line above)
          #uri: file://home/jorge/git/microspring11-security-lab10/microspring11-local-git-repository-lab10 #Local git repository where microspring11-cloud-client-lab10.yml file exists

server: 
  port: 8001
  